# Import the vital libraries 

In [188]:
import numpy as np
import pandas as pd 
import seaborn as sns 
import matplotlib.pyplot as plt 

import os


os.getcwd()

os.chdir('C:\\Users\\Amit177766\\OneDrive - EXLService.com (I) Pvt. Ltd\\Desktop\\Data\\Data')



# Import the  dataset 

In [189]:
ir=pd.read_csv('Iris.csv')

ir.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [190]:
ir.drop(labels="Id",inplace=True, axis =1 )

# Commands to explore data


In [191]:
ir.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

# Head ,tail 

# How do you call a Varibale in the table ? Drill down . 

In [192]:
ir.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa

In [193]:
# ir.SepalLengthCm

# Discover the data type in Python : Collective and singular .

# Some of the functions used with list : append , insert , remove , Index , count, sort , reverse , range 

In [194]:
x= [23.3,{"Name":"Sumit", "Age":34},{34,89}, (34,89) ]

x

[23.3, {'Name': 'Sumit', 'Age': 34}, {34, 89}, (34, 89)]

In [195]:
x.append(45)
x



[23.3, {'Name': 'Sumit', 'Age': 34}, {34, 89}, (34, 89), 45]

In [196]:
x.index({'Name':'Sumit','Age':34})

1

In [197]:
x.remove(45)

In [198]:
# Built in functions in Python important ones : abs , dict, dir, int , float , help , id , input ,  len , list , range, round, sorted (list), sum(range(), type()) 

In [199]:
abs(-35)

dict(Name='Sumit',Age=34)

# help(pd)

range(10)

range(0, 10)

# Expolre the Escape characters \ , \\ , \n ,\t , \b  

In [200]:
x= "Hi how are \t you "
print(x)

Hi how are 	 you 



# Slicing of data : iloc , loc , []

Use iloc to extract first six rows from the data set  and columns  from 'SepalLengthCm' to 'PetalWidthCm'

In [201]:
ir.head(10)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa
5            5.4           3.9            1.7           0.4  Iris-setosa
6            4.6           3.4            1.4           0.3  Iris-setosa
7            5.0           3.4            1.5           0.2  Iris-setosa
8            4.4           2.9            1.4           0.2  Iris-setosa
9            4.9           3.1            1.5           0.1  Iris-setosa

In [202]:
ir.iloc[0 :6 ,1 :4 ]

SepalWidthCm  PetalLengthCm  PetalWidthCm
0           3.5            1.4           0.2
1           3.0            1.4           0.2
2           3.2            1.3           0.2
3           3.1            1.5           0.2
4           3.6            1.4           0.2
5           3.9            1.7           0.4

In [203]:
ir.head(10)

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0            5.1           3.5            1.4           0.2  Iris-setosa
1            4.9           3.0            1.4           0.2  Iris-setosa
2            4.7           3.2            1.3           0.2  Iris-setosa
3            4.6           3.1            1.5           0.2  Iris-setosa
4            5.0           3.6            1.4           0.2  Iris-setosa
5            5.4           3.9            1.7           0.4  Iris-setosa
6            4.6           3.4            1.4           0.3  Iris-setosa
7            5.0           3.4            1.5           0.2  Iris-setosa
8            4.4           2.9            1.4           0.2  Iris-setosa
9            4.9           3.1            1.5           0.1  Iris-setosa

In [204]:
ir.loc[0:5 ,['SepalWidthCm' ,'PetalWidthCm']

SyntaxError: unexpected EOF while parsing (<ipython-input-204-3ea76f00ba27>, line 1)

# Use loc command to extract rows 10 to 15 and columns 'SepalLengthCm' to 'PetalWidthCm'

In [ ]:
ir.head(10)

In [ ]:
ir[0:6][['PetalWidthCm']]

# Opertors in Python  

In [ ]:
# Arthmetic operators , Relational Operators > < >= , == ,!=   Assignment operator =, += ,*=, /=, % = ,**= , Identity operator = is , is not , membership = in , not in  

x=5.1

x is 5.1 


# x is 5.1

# print(id(x))

# print(id(5.1))

In [ ]:
"Amit" is "Amit"

In [ ]:
ir.SepalLengthCm[0]=5.1

In [ ]:
ir.SepalLengthCm[0] is 5.1

print(id(ir.SepalLengthCm))
print(id(5.1))

# 2495694544176

In [ ]:
ir.SepalLengthCm[0] == 5.1


# Find the mean of SepalLength for the entire data set and add the value to a variable 

In [ ]:
# ir.SepalLengthCm.mean()+ir.SepalWidthCm

In [ ]:
# Polymorphism property : means having many forms 

# Identity operator is and not is 
Create two objects having same values and see if the is operator returns True . 
Note : 'is' Operator checks if two objects are same or not 


# Functions- user defined -including -Inbuilt functions in Python ,lambda & Enumerate   


# Create a function to check which number is greater than the other .

In [ ]:
def  myfunc(x,y=45):
    if x>y :
        print("%d  is greater than %d"%(x,y))
    else:
        print("y={} is greater than x={}".format(y,x))

In [ ]:
myfunc(355,500)

# Groupby , count , value counts

# Group the data into different species and check the average values for each of the categories  in species . Iris-setosa , Iris-versicolor ,Iris-virginica

In [ ]:
ir.head(10)

ir.Species.value_counts()

ir.groupby(by='Species').sum()


# groupby works on the principal of cut and apply 

# Condition : if elif else 

In [ ]:
ir.head()

# for & while:
Task check if sepal length is greater than 5.1 then print 'full length' , if it is greater than 3.5 but less than 5.1 then 'medium' and if it is less than 3.1 then 'small' 

# while loop :Task assign  x= 1000 y =10 print the number x till the time it is greater than y . Reduce the number x in each iteration by 100 

In [209]:
# while and for loop 
x= 1000
y=100

while x > y: # Loop stops iterrating when the condition becomes false 
    print(x)
    x-= 100
    
    


1000
900
800
700
600
500
400
300
200


# Exception 

In [ ]:
ZeroDivisionError 1\0
NameError- using a variable that is not decalred -print(a)  no refernce to a earlier .
AttributeError- attaching an attribute that does not exist - ir.describ()

# Check if a triangle is an Isosceles triangle  or not ? 

In [214]:
# x,y,z three sides of the traingle 

x=201
y=201
z=200

# if , elif , else 
# Nested loop 

if x==y:
    if y==z:
        print("Not an Iso")
    else:
        print("Is an Isosceles triangle ")
elif x==z:
    print("Is an Isoscles triangle ")

elif y==z: 
    print("Is an Isoscles traingle ")
    
else:
    print("Not an Isoscles traingle")
    
    
    
    
    

        
        
    




Is an Isosceles triangle 


# Use the inbuilt function range to generate values from 0-9
# use numpy also to generate the same 

In [215]:
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [220]:
15 % 3

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

# Check if a number is prime or not ()

In [228]:
x= 25
2,x-1

n=np.arange(2,x)

# 25 % 5


for i in n : 
    if x % i==0:
        print("Not a prime number ")
        break
        
    else:
        if i !=x-1:
            continue 
        else:
            print("Is a prime number ")


Not a prime number 


# List Expression [identifier  for loop if loop  ]  
# Check if an  integer number (between 1-100) is  divisible by 8   

In [244]:
np.arange(1,101)

# for i in np.arange(1,101):
#     if i % 8 ==0:
#         print(i)

[i for i in np.arange(1,101) if i%8==0]

# check if else can be used with a list expression 
'6' in '26' 

True

In [245]:
np.arange(0,101)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

# Check how many numbers have digit  6 ( between 0-100) 

In [260]:
[i for i in np.arange(0,101) if "6" in str(i)]

[6, 16, 26, 36, 46, 56, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 76, 86, 96]

# Check how many spaces are there in a string

In [255]:
x= " Hi how are you doing today "

[i for i in x if i==' ']



7

In [256]:
# *****
# ****
# ***
# **
# *

# using only while loop 



In [258]:
'6' in '1006'

True